/*
 * Alistair Jewers
 * 
 * Copyright (c) 2015 Sofia Software Solutions. All Rights Reserved. 
 */
package teacheasy.xml.util;

import java.util.ArrayList;

/**
 * Encapsulates a notification generated by the XML parser, either
 * a warning or an error. This includes a textual description of
 * the problem.
 * 
 * @author Alistair Jewers
 * @version 1.0 09 Apr 2015
 */
public class XMLNotification {
    /** Enumerates the different types of notification */
    public enum Level {
        WARNING,
        ERROR
    }
    
    /** The level of this notification */
    private Level level;
    
    /** The description of the problem */
    private String text;
    
    /**
     * Constructor.
     * 
     * @param nLevel The level of the notification.
     * @param nText The description.
     */
    public XMLNotification(Level nLevel, String nText) {
        this.level = nLevel;
        this.text = nText;
    }
    
    /**
     * Gets the description text.
     */
    public String getText() {
        return text;
    }
    
    /**
     * Gets the level of the notification.
     */
    public Level getLevel() {
        return level;
    }
    
    /**
     * Returns the notification in string form.
     */
    @Override
    public String toString() {
        return new String("[" + level.toString() + "] " + text);
    }
    
    /**
     * Static method to check the number of certain notification types in
     * an error list.
     * 
     * @param errorList An array list of notifications.
     * @param level The level to count.
     * @return The number of notifications in 'errorList' of level 'level'.
     */
    public static int countLevel(ArrayList<XMLNotification> errorList, Level level) {
        int n = 0;
        
        for(XMLNotification i : errorList) {
            if(i.getLevel() == level) {
                n++;
            }
        }
        
        return n;
    }
}
